---
# Ручной запуск: pre-commit run -a
# Hooks list: https://pre-commit.com/hooks.html
repos:
    # GitLeaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.0
    hooks:
      - id: gitleaks

    # Общая проверка
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

    # Terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
      - id: terraform_tfsec
      - id: terraform_tflint

    # YAML
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.9.0
    hooks:
      - id: yamlfix
        exclude: .github/workflows/

    # git lint
    #- repo: https://github.com/jorisroovers/gitlint
    # rev: v0.18.0
    # hooks:
    #- id: gitlint
    # name: Commit message lint
    # description: Проверяет, что сообщение к коммиту
    # соответсвует соглашениям
    # exclude: README.md
